// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

import {VRFConsumerBaseV2Plus} from "@chainlink/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol";
import {VRFV2PlusClient} from "@chainlink/contracts/src/v0.8/vrf/dev/libraries/VRFV2PlusClient.sol";

error RandomIpfsNft__NotContractOwner();
error RandomIpfsNft__NotEnoughEthSent();
error RandomIpfsNft__TransferFailed();

/**
 * @title A contract for minting random IPFS NFTs using Chainlink VRF
 * @author Paul Lam
 * @notice This contract allows users to request a random NFT, which will be minted based on a random breed determined by Chainlink VRF. The contract owner can withdraw the accumulated funds from minting fees.
 * @dev This contract uses Chainlink VRF v2 to generate random numbers and determine the breed of the NFT to be minted. The contract also includes error handling for insufficient payment and transfer failures.
 */
contract RandomIpfsNft is VRFConsumerBaseV2Plus {
    enum Breed {
        PUG,
        SHIBA_INU,
        ST_BERNARD
    }

    uint16 private constant REQUEST_CONFIRMATIONS = 3;

    uint256 private immutable I_REQUEST_FEE;
    bytes32 private immutable I_GAS_LANE;
    uint256 private immutable I_SUBSCRIPTION_ID;
    uint32 private immutable I_CALLBACK_GAS_LIMIT;

    address private immutable I_OWNER;
    uint256 private s_tokenCounter;
    uint16[] private s_breedPercentages = [10, 30, 100];

    mapping(uint256 => Breed) private s_tokenIdToBreed;
    mapping(uint256 => address) private s_requestIdToSender;
    mapping(address => uint256[]) private s_minterToTokenIds;

    /**
     * @notice Emitted when a random breed is requested, logging the request ID and the address of the requester.
     * @param requestId The unique identifier for the random breed request.
     * @param requester The address of the user who requested the random breed.
     */
    event RandomBreedRequested(
        uint256 indexed requestId,
        address indexed requester
    );

    /**
     * @notice Emitted when an NFT is requested, logging the request ID and the address of the requester.
     * @param requestId The unique identifier for the NFT request.
     * @param requester The address of the user who requested the NFT.
     */
    event NftRequested(uint256 indexed requestId, address indexed requester);

    /**
     * @notice Emitted when an NFT is minted, logging the breed of the NFT and the address of the minter.
     * @param breed The breed of the NFT that was minted.
     * @param minter The address of the user who minted the NFT.
     */
    event NftMinted(Breed breed, address minter);

    modifier onlyContractOwner() {
        if (msg.sender != I_OWNER) {
            revert RandomIpfsNft__NotContractOwner();
        }
        _;
    }

    constructor(
        address vrfCoordinator,
        uint256 requestFee,
        bytes32 gasLane,
        uint256 subscriptionId,
        uint32 callbackGasLimit
    ) VRFConsumerBaseV2Plus(vrfCoordinator) {
        I_REQUEST_FEE = requestFee;
        I_GAS_LANE = gasLane;
        I_SUBSCRIPTION_ID = subscriptionId;
        I_CALLBACK_GAS_LIMIT = callbackGasLimit;

        I_OWNER = msg.sender;
        s_tokenCounter = 0;
    }

    /**
     * @notice Allows users to request a random NFT by paying the required fee. The function checks if the sent value is sufficient and then initiates a request for a random breed using Chainlink VRF. An event is emitted to log the request.
     */
    function requestNft() public payable {
        if (msg.value < I_REQUEST_FEE) {
            revert RandomIpfsNft__NotEnoughEthSent();
        }

        uint256 requestId = requestRandomBreed(false);
        emit RandomBreedRequested(requestId, msg.sender);
    }

    /**
     * @notice Internal function that initiates a request for a random breed using Chainlink VRF. It constructs the request with the necessary parameters and stores the mapping of the request ID to the sender's address. The function returns the unique request ID generated by Chainlink VRF.
     * @param enableNativePayment A boolean indicating whether to enable native payment for the VRF request.
     * @return requestId The unique identifier for the random breed request generated by Chainlink VR
     */
    function requestRandomBreed(
        bool enableNativePayment
    ) internal returns (uint256 requestId) {
        requestId = s_vrfCoordinator.requestRandomWords(
            VRFV2PlusClient.RandomWordsRequest({
                keyHash: I_GAS_LANE,
                subId: I_SUBSCRIPTION_ID,
                requestConfirmations: REQUEST_CONFIRMATIONS,
                callbackGasLimit: I_CALLBACK_GAS_LIMIT,
                numWords: 1,
                extraArgs: VRFV2PlusClient._argsToBytes(
                    VRFV2PlusClient.ExtraArgsV1({
                        nativePayment: enableNativePayment
                    })
                )
            })
        );
        s_requestIdToSender[requestId] = msg.sender;
    }

    /**
     * @notice Internal function that is called by Chainlink VRF when the random words are fulfilled. It determines the breed of the NFT based on the random number received, mints the NFT to the requester, and updates the relevant mappings. An event is emitted to log the minting of the NFT.
     * @param requestId The unique identifier for the random breed request.
     * @param randomWords An array of random words generated by Chainlink VRF, where the first element is used to determine the breed of the NFT.
     */
    function fulfillRandomWords(
        uint256 requestId,
        uint256[] calldata randomWords
    ) internal override {
        uint256 chance = randomWords[0] % 100;
        Breed breed = getBreedFromChance(chance);
        address minter = s_requestIdToSender[requestId];
        uint256 tokenId = s_tokenCounter;

        s_tokenIdToBreed[tokenId] = breed;
        s_minterToTokenIds[minter].push(tokenId);
        ++s_tokenCounter;

        emit NftMinted(breed, minter);
    }

    /**
     * @notice Internal function that determines the breed of the NFT based on the provided chance value. It iterates through the breed percentages to find the appropriate breed corresponding to the chance value. If the chance value is less than a certain percentage, it returns the corresponding breed; otherwise, it returns the last breed in the list.
     * @param chance A uint256 value representing the chance used to determine the breed of the
     * NFT, typically derived from a random number generated by Chainlink VRF.
     * @return breed The determined breed of the NFT based on the chance value.
     */
    function getBreedFromChance(uint256 chance) internal view returns (Breed) {
        for (uint16 i = 0; i < s_breedPercentages.length; ++i) {
            if (chance < s_breedPercentages[i]) {
                return Breed(i);
            }
        }
        return Breed(s_breedPercentages.length - 1);
    }

    /**
     * @notice Allows the contract owner to withdraw the accumulated funds from minting fees. The function checks if the caller is the contract owner and then transfers the entire balance of the contract to the owner's address. If the transfer fails, it reverts with an error.
     */
    function withdraw() public onlyContractOwner {
        uint256 balance = address(this).balance;
        (bool success, ) = payable(I_OWNER).call{value: balance}("");
        if (!success) {
            revert RandomIpfsNft__TransferFailed();
        }
    }

    /**
     * @notice Public view function that returns the request fee required to request a random NFT. This function allows users to check the fee before making a request.
     * @return The fee in wei required to request a random NFT.
     */
    function getRequestFee() public view returns (uint256) {
        return I_REQUEST_FEE;
    }

    /**
     * @notice Public view function that returns the gas lane (key hash) used for the Chainlink VRF request. This function allows users to check the gas lane before making a request.
     * @return The bytes32 value representing the gas lane (key hash) used for the Chainlink VRF request.
     */
    function getGasLane() public view returns (bytes32) {
        return I_GAS_LANE;
    }

    /**
     * @notice Public view function that returns the callback gas limit used for the Chainlink VRF request. This function allows users to check the callback gas limit before making a request.
     * @return The uint32 value representing the callback gas limit used for the Chainlink VRF request.
     */
    function getCallbackGasLimit() public view returns (uint32) {
        return I_CALLBACK_GAS_LIMIT;
    }
}
